### ISSUE TITLE
Support "none" preset?

### ISSUE THREAD

**Issue by jaydiablo** [Soullivaneuh/styleci-fixers#13]
I realize this preset isn't returned from the styleci API:

https://api.styleci.io/presets

But it is listed in their documentation as an allowed preset:

https://styleci.readme.io/v1.0/docs/presets

> We also have an additional preset, none, which enables no fixers.

Currently if I specify "none" in the .styleci.yml, and process it with the php-cs-fixer bridge, I get an exception:

> [Symfony\Component\Config\Definition\Exception\InvalidConfigurationException]
>   The value "none" is not allowed for path "styleci.preset". Permissible values: "psr1", "psr2", "symfony", "laravel", "recommended"

Thoughts to add this as an allowed preset?

**Comment by soullivaneuh** [comment]
Hi @jaydiablo and thanks for the report.

As you said, the `none` preset is not given by the API.

I think it's "normal" because the `none` preset does not have any fixer. Can you please confirm that @GrahamCampbell?

IMO, nothing have to be done here because this package is just a generator form the API.

But the `none` preset could be added here: https://github.com/Soullivaneuh/php-cs-fixer-styleci-bridge/blob/v2.0.2/src/StyleCI/Configuration.php

**Comment by GrahamCampbell** [comment]
> I think it's "normal" because the none preset does not have any fixer. Can you please confirm that @GrahamCampbell?

Yes, the idea is that it does nothing.

**Comment by GrahamCampbell** [comment]
It's implemented as a special case higher up in the abstraction, which is why it's not showing up on our API.

**Comment by GrahamCampbell** [comment]
It's also treated as a special case in our docs: https://styleci.readme.io/docs/presets.

**Comment by soullivaneuh** [comment]
Thanks @GrahamCampbell, this confirm what I was thinking.

@jaydiablo I'll update the bridge instead.

**Comment by jaydiablo** [comment]
@Soullivaneuh thanks!

**Comment by soullivaneuh** [comment]
@jaydiablo please see: https://github.com/Soullivaneuh/php-cs-fixer-styleci-bridge/pull/67
